
// Generated by https://quicktype.io
// interface for https://grandcircusco.github.io/demo-apis/donuts.json  created using Paste JSON as Code

export interface Donut {
    id:                number;
    ref:               string;
    name:              string;
    photo:             string;
    photo_attribution: string;

}
