
// Generated by https://quicktype.io
// interface for https://grandcircusco.github.io/demo-apis/donuts.json  created using Paste JSON as Code

// export interface People { 
//     firstName:  string;
//     lastName:   string;
//     innovation: string;
//     year:       number;
// }


export interface People {
    complete: Complete[];
    tiny:     Tiny[];
}

export interface Complete {
    firstName:  string;
    lastName:   string;
    innovation: string;
    year:       number;
}

export interface Tiny {
    name:     string;
    invented: string;
    year:     number;
}
